apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vote
  namespace: default
spec:
  ingressClassName: webapprouting.kubernetes.azure.com
  rules:
  - host: <Hostname>
    http:
      paths:
      - backend:
          service:
            name: azure-vote-front
            port:
              number: 80
        path: /
        pathType: Prefix